version: "3"

networks:
    pattern_net:

# använd: docker build -t neskoc/pattern:backend -f Dockerfile.api . 
services:
    backend:
        image: neskoc/pattern:backend
        container_name: "backend"
        expose:
            - "1337"
        ports:
            - "127.0.0.1:1337:1337"
        networks:
            - pattern_net
        # volumes:
        #    - ./api:/api
        restart:
            "always"

    esc:
        image: neskoc/pattern:esc
        container_name: "esc"
        expose:
            - "8000"
        ports:
            - "127.0.0.1:8000:8000"
        networks:
            - pattern_net
        links:
            - backend
        depends_on:
            - backend

    admin:
        image: neskoc/pattern:admin
        container_name: "admin"
        ports:
            - "127.0.0.1:1337:1338"
        networks:
            - pattern_net
        links:
            - backend
        depends_on:
            - backend

    app:
        image: neskoc/pattern:app
        container_name: "app"
        ports:
            - "127.0.0.1:1337:1339"
        networks:
            - pattern_net
        links:
            - backend
        depends_on:
            - backend
